-- Extended Rose Catalog
-- Run AFTER 004_rose_metadata.sql
-- ~120 additional verified varieties with full metadata
-- Uses ON CONFLICT DO NOTHING so existing entries are never overwritten

insert into rose_entities
  (canonical_name, breeder_code, class_code, color_code, growth_type, pruning_model, plant_structure_type, year_introduced, country_of_origin, species)
values

-- ── HYBRID TEAS (additional) ───────────────────────────────────────────────
('Chrysler Imperial',    null,  'HT', 'dr', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1952, 'United States',    'Rosa x hybrida'),
('Tiffany',              null,  'HT', 'pb', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1954, 'United States',    'Rosa x hybrida'),
('Fragrant Cloud',       'TAN', 'HT', 'or', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1963, 'Germany',          'Rosa x hybrida'),
('John F. Kennedy',      'JAC', 'HT', 'w',  'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1965, 'United States',    'Rosa x hybrida'),
('Oklahoma',             null,  'HT', 'dr', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1964, 'United States',    'Rosa x hybrida'),
('Garden Party',         null,  'HT', 'ab', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1959, 'United States',    'Rosa x hybrida'),
('Pink Peace',           'MEI', 'HT', 'dp', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1959, 'France',           'Rosa x hybrida'),
('First Prize',          null,  'HT', 'pb', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1970, 'United States',    'Rosa x hybrida'),
('Pristine',             'JAC', 'HT', 'w',  'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1978, 'United States',    'Rosa x hybrida'),
('Pascali',              null,  'HT', 'w',  'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1963, 'Belgium',          'Rosa x hybrida'),
('Ingrid Bergman',       null,  'HT', 'dr', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1984, 'Denmark',          'Rosa x hybrida'),
('Kardinal',             'KOR', 'HT', 'mr', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1985, 'Germany',          'Rosa x hybrida'),
('Elina',                'DIC', 'HT', 'ly', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1983, 'Northern Ireland', 'Rosa x hybrida'),
('Just Joey',            null,  'HT', 'ab', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1972, 'England',          'Rosa x hybrida'),
('St. Patrick',          'WEK', 'HT', 'my', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1996, 'United States',    'Rosa x hybrida'),
('Chicago Peace',        null,  'HT', 'pb', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1962, 'United States',    'Rosa x hybrida'),
('Silver Jubilee',       'COC', 'HT', 'ab', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1978, 'Scotland',         'Rosa x hybrida'),
('Alexander',            'HAR', 'HT', 'or', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1972, 'England',          'Rosa x hybrida'),
('Electron',             null,  'HT', 'dp', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1970, 'Northern Ireland', 'Rosa x hybrida'),
('Keepsake',             'KOR', 'HT', 'pb', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1981, 'Germany',          'Rosa x hybrida'),
('Papa Meilland',        'MEI', 'HT', 'dr', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1963, 'France',           'Rosa x hybrida'),
('Helmut Schmidt',       'KOR', 'HT', 'my', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1979, 'Germany',          'Rosa x hybrida'),
('Marijke Koopman',      'FRY', 'HT', 'dp', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1979, 'England',          'Rosa x hybrida'),
('Veteran''s Honor',     'JAC', 'HT', 'mr', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1999, 'United States',    'Rosa x hybrida'),
('Falling in Love',      'JAC', 'HT', 'pb', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1999, 'United States',    'Rosa x hybrida'),
('Pope John Paul II',    'JAC', 'HT', 'w',  'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 2006, 'United States',    'Rosa x hybrida'),
('Firefighter',          'KOR', 'HT', 'dr', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 2002, 'Germany',          'Rosa x hybrida'),
('Let Freedom Ring',     'WEK', 'HT', 'mr', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 2009, 'United States',    'Rosa x hybrida'),
('Rosie the Riveter',    'WEK', 'HT', 'ob', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 2019, 'United States',    'Rosa x hybrida'),
('La France',            null,  'HT', 'pb', 'hybrid_tea', 'NEW_GROWTH_DOMINANT', 'cane', 1867, 'France',           'Rosa x hybrida'),

-- ── GRANDIFLORAS ──────────────────────────────────────────────────────────
('Queen Elizabeth',      null,  'G',  'mp', 'grandiflora', 'NEW_GROWTH_DOMINANT', 'cane', 1954, 'United States',   'Rosa x hybrida'),
('Shreveport',           'KOR', 'G',  'ob', 'grandiflora', 'NEW_GROWTH_DOMINANT', 'cane', 1981, 'Germany',         'Rosa x hybrida'),
('Tournament of Roses',  'JAC', 'G',  'mp', 'grandiflora', 'NEW_GROWTH_DOMINANT', 'cane', 1988, 'United States',   'Rosa x hybrida'),
('Montezuma',            null,  'G',  'or', 'grandiflora', 'NEW_GROWTH_DOMINANT', 'cane', 1955, 'United States',   'Rosa x hybrida'),

-- ── FLORIBUNDAS ───────────────────────────────────────────────────────────
('Iceberg',              'KOR', 'F',  'w',  'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1958, 'Germany',          'Rosa x hybrida'),
('Angel Face',           null,  'F',  'm',  'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1968, 'United States',    'Rosa x hybrida'),
('Betty Prior',          null,  'F',  'mp', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1935, 'England',          'Rosa x hybrida'),
('Europeana',            'HOR', 'F',  'dr', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1963, 'Netherlands',      'Rosa x hybrida'),
('French Lace',          'JAC', 'F',  'w',  'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1980, 'United States',    'Rosa x hybrida'),
('Livin'' Easy',         'HAR', 'F',  'ob', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1992, 'England',          'Rosa x hybrida'),
('Sexy Rexy',            null,  'F',  'mp', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1984, 'New Zealand',      'Rosa x hybrida'),
('Trumpeter',            null,  'F',  'or', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1977, 'New Zealand',      'Rosa x hybrida'),
('Cherish',              'JAC', 'F',  'mp', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1980, 'United States',    'Rosa x hybrida'),
('Simplicity',           'JAC', 'F',  'mp', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1978, 'United States',    'Rosa x hybrida'),
('Class Act',            'JAC', 'F',  'w',  'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1988, 'United States',    'Rosa x hybrida'),
('Singin'' in the Rain', null,  'F',  'ab', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1994, 'New Zealand',      'Rosa x hybrida'),
('Showbiz',              'TAN', 'F',  'mr', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1983, 'Germany',          'Rosa x hybrida'),
('Nearly Wild',          null,  'F',  'mp', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1941, 'United States',    'Rosa x hybrida'),
('Julia Child',          'WEK', 'F',  'my', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 2004, 'United States',    'Rosa x hybrida'),
('Cinco de Mayo',        'WEK', 'F',  'ob', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 2008, 'United States',    'Rosa x hybrida'),
('Hot Cocoa',            'WEK', 'F',  'ob', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 2003, 'United States',    'Rosa x hybrida'),
('Day Breaker',          'FRY', 'F',  'ab', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 2004, 'England',          'Rosa x hybrida'),
('Impatient',            'JAC', 'F',  'or', 'floribunda', 'NEW_GROWTH_DOMINANT', 'cane', 1982, 'United States',    'Rosa x hybrida'),

-- ── CLIMBERS (additional) ─────────────────────────────────────────────────
('New Dawn',             null,  'Cl HT', 'lp', 'climber', 'MIXED_CANE', 'cane', 1930, 'United States',            'Rosa x hybrida'),
('Blaze',                null,  'Cl HT', 'mr', 'climber', 'MIXED_CANE', 'cane', 1932, 'United States',            'Rosa x hybrida'),
('America',              'JAC', 'Cl HT', 'ob', 'climber', 'MIXED_CANE', 'cane', 1976, 'United States',            'Rosa x hybrida'),
('Fourth of July',       'WEK', 'Cl HT', 'rb', 'climber', 'MIXED_CANE', 'cane', 1999, 'United States',            'Rosa x hybrida'),
('Climbing Iceberg',     null,  'Cl F',  'w',  'climber', 'MIXED_CANE', 'cane', 1968, 'Australia',                'Rosa x hybrida'),
('Joseph''s Coat',       null,  'Cl HT', 'yb', 'climber', 'MIXED_CANE', 'cane', 1964, 'United States',            'Rosa x hybrida'),
('Altissimo',            'DEL', 'Cl HT', 'mr', 'climber', 'MIXED_CANE', 'cane', 1966, 'France',                   'Rosa x hybrida'),
('High Hopes',           'HAR', 'Cl HT', 'lp', 'climber', 'MIXED_CANE', 'cane', 1992, 'England',                  'Rosa x hybrida'),
('Dublin Bay',           null,  'Cl HT', 'mr', 'climber', 'MIXED_CANE', 'cane', 1975, 'New Zealand',              'Rosa x hybrida'),
('Cl. Cecile Brunner',   null,  'Cl Pol','lp', 'climber', 'MIXED_CANE', 'cane', 1894, 'United States',            'Rosa x hybrida'),
('Handel',               'McG', 'Cl HT', 'pb', 'climber', 'MIXED_CANE', 'cane', 1965, 'Northern Ireland',         'Rosa x hybrida'),

-- ── SHRUBS / LANDSCAPE ────────────────────────────────────────────────────
('Knock Out',            'RAD', 'S', 'mr', 'shrub', 'NEW_GROWTH_DOMINANT', 'cane', 2000, 'United States',         'Rosa x hybrida'),
('Pink Knock Out',       'RAD', 'S', 'mp', 'shrub', 'NEW_GROWTH_DOMINANT', 'cane', 2004, 'United States',         'Rosa x hybrida'),
('Double Knock Out',     'RAD', 'S', 'mr', 'shrub', 'NEW_GROWTH_DOMINANT', 'cane', 2004, 'United States',         'Rosa x hybrida'),
('Carefree Beauty',      'BUC', 'S', 'mp', 'shrub', 'NEW_GROWTH_DOMINANT', 'cane', 1977, 'United States',         'Rosa x hybrida'),
('Carefree Wonder',      'MEI', 'S', 'pb', 'shrub', 'NEW_GROWTH_DOMINANT', 'cane', 1990, 'France',                'Rosa x hybrida'),
('Bonica',               'MEI', 'S', 'lp', 'shrub', 'NEW_GROWTH_DOMINANT', 'cane', 1985, 'France',                'Rosa x hybrida'),
('The Fairy',            null,  'S', 'lp', 'shrub', 'NEW_GROWTH_DOMINANT', 'cane', 1932, 'England',               'Rosa x hybrida'),
('Ballerina',            null,  'HMsk', 'mp', 'shrub', 'NEW_GROWTH_DOMINANT', 'stem_cluster', 1937, 'England',    'Rosa x hybrida'),
('Buff Beauty',          null,  'HMsk', 'ab', 'shrub', 'MIXED_CANE', 'cane', 1939, 'England',                     'Rosa x hybrida'),
('Sea Foam',             null,  'S', 'w', 'shrub', 'MIXED_CANE', 'cane', 1964, 'United States',                   'Rosa x hybrida'),
('Scarlet Meidiland',    'MEI', 'S', 'mr', 'shrub', 'NEW_GROWTH_DOMINANT', 'cane', 1987, 'France',                'Rosa x hybrida'),
('Pink Meidiland',       'MEI', 'S', 'mp', 'shrub', 'NEW_GROWTH_DOMINANT', 'cane', 1983, 'France',                'Rosa x hybrida'),

-- ── DAVID AUSTIN ENGLISH ROSES ────────────────────────────────────────────
('Graham Thomas',              'AUS', 'S', 'dy', 'shrub', 'MIXED_CANE', 'cane', 1983, 'England', 'Rosa x hybrida'),
('Heritage',                   'AUS', 'S', 'lp', 'shrub', 'MIXED_CANE', 'cane', 1984, 'England', 'Rosa x hybrida'),
('Mary Rose',                  'AUS', 'S', 'mp', 'shrub', 'MIXED_CANE', 'cane', 1983, 'England', 'Rosa x hybrida'),
('Abraham Darby',              'AUS', 'S', 'ab', 'shrub', 'MIXED_CANE', 'cane', 1985, 'England', 'Rosa x hybrida'),
('Gertrude Jekyll',            'AUS', 'S', 'dp', 'shrub', 'MIXED_CANE', 'cane', 1986, 'England', 'Rosa x hybrida'),
('Winchester Cathedral',       'AUS', 'S', 'w',  'shrub', 'MIXED_CANE', 'cane', 1988, 'England', 'Rosa x hybrida'),
('The Prince',                 'AUS', 'S', 'dr', 'shrub', 'MIXED_CANE', 'cane', 1990, 'England', 'Rosa x hybrida'),
('Evelyn',                     'AUS', 'S', 'ab', 'shrub', 'MIXED_CANE', 'cane', 1991, 'England', 'Rosa x hybrida'),
('Pat Austin',                 'AUS', 'S', 'ob', 'shrub', 'MIXED_CANE', 'cane', 1995, 'England', 'Rosa x hybrida'),
('Jude the Obscure',           'AUS', 'S', 'ab', 'shrub', 'MIXED_CANE', 'cane', 1995, 'England', 'Rosa x hybrida'),
('William Shakespeare 2000',   'AUS', 'S', 'dr', 'shrub', 'MIXED_CANE', 'cane', 2000, 'England', 'Rosa x hybrida'),
('Falstaff',                   'AUS', 'S', 'mr', 'shrub', 'MIXED_CANE', 'cane', 1999, 'England', 'Rosa x hybrida'),
('Charlotte',                  'AUS', 'S', 'ly', 'shrub', 'MIXED_CANE', 'cane', 1993, 'England', 'Rosa x hybrida'),
('Tess of the d''Urbervilles', 'AUS', 'S', 'mr', 'shrub', 'MIXED_CANE', 'cane', 1998, 'England', 'Rosa x hybrida'),
('Olivia Rose',                'AUS', 'S', 'lp', 'shrub', 'MIXED_CANE', 'cane', 2014, 'England', 'Rosa x hybrida'),
('Darcey Bussell',             'AUS', 'S', 'mr', 'shrub', 'MIXED_CANE', 'cane', 2006, 'England', 'Rosa x hybrida'),
('Princess Alexandra of Kent', 'AUS', 'S', 'dp', 'shrub', 'MIXED_CANE', 'cane', 2007, 'England', 'Rosa x hybrida'),
('Gentle Hermione',            'AUS', 'S', 'lp', 'shrub', 'MIXED_CANE', 'cane', 2005, 'England', 'Rosa x hybrida'),
('Munstead Wood',              'AUS', 'S', 'dr', 'shrub', 'MIXED_CANE', 'cane', 2007, 'England', 'Rosa x hybrida'),
('Lichfield Angel',            'AUS', 'S', 'w',  'shrub', 'MIXED_CANE', 'cane', 2006, 'England', 'Rosa x hybrida'),
('Roald Dahl',                 'AUS', 'S', 'ab', 'shrub', 'MIXED_CANE', 'cane', 2016, 'England', 'Rosa x hybrida'),
('The Poet''s Wife',           'AUS', 'S', 'my', 'shrub', 'MIXED_CANE', 'cane', 2014, 'England', 'Rosa x hybrida'),
('Scepter''d Isle',            'AUS', 'S', 'lp', 'shrub', 'MIXED_CANE', 'cane', 1996, 'England', 'Rosa x hybrida'),

-- ── OLD GARDEN ROSES ──────────────────────────────────────────────────────
('Tuscany Superb',        null, 'Ga',  'dr', 'old_garden', 'OLD_WOOD_SENSITIVE', 'cane',         1837, 'England',     'Rosa gallica'),
('Cardinal de Richelieu', null, 'Ga',  'm',  'old_garden', 'OLD_WOOD_SENSITIVE', 'stem_cluster', 1840, 'Netherlands', 'Rosa gallica'),
('Rosa Mundi',            null, 'Ga',  'pb', 'old_garden', 'OLD_WOOD_SENSITIVE', 'stem_cluster', null, 'England',     'Rosa gallica versicolor'),
('Madame Hardy',          null, 'D',   'w',  'old_garden', 'OLD_WOOD_SENSITIVE', 'cane',         1832, 'France',      'Rosa x damascena'),
('Reine des Violettes',   null, 'HP',  'm',  'old_garden', 'MIXED_CANE',         'cane',         1860, 'France',      'Rosa x hybrida'),
('General Jacqueminot',   null, 'HP',  'mr', 'old_garden', 'MIXED_CANE',         'cane',         1853, 'France',      'Rosa x hybrida'),
('Souvenir de la Malmaison', null, 'B','lp', 'old_garden', 'OLD_WOOD_SENSITIVE', 'cane',         1843, 'France',      'Rosa x hybrida'),
('Louise Odier',          null, 'B',   'dp', 'old_garden', 'MIXED_CANE',         'cane',         1851, 'France',      'Rosa x hybrida'),
('Paul Neyron',           null, 'HP',  'dp', 'old_garden', 'MIXED_CANE',         'cane',         1869, 'France',      'Rosa x hybrida'),
('Baronne Prevost',       null, 'HP',  'lp', 'old_garden', 'MIXED_CANE',         'cane',         1842, 'France',      'Rosa x hybrida'),
('Fantin-Latour',         null, 'C',   'lp', 'old_garden', 'OLD_WOOD_SENSITIVE', 'cane',         null, 'England',     'Rosa x centifolia'),
('William Lobb',          null, 'M',   'm',  'old_garden', 'OLD_WOOD_SENSITIVE', 'cane',         1855, 'France',      'Rosa x centifolia muscosa'),
('Charles de Mills',      null, 'Ga',  'rb', 'old_garden', 'OLD_WOOD_SENSITIVE', 'stem_cluster', null, 'Netherlands', 'Rosa gallica'),
('Autumn Damask',         null, 'D',   'mp', 'old_garden', 'OLD_WOOD_SENSITIVE', 'cane',         null, 'Unknown',     'Rosa x damascena bifera'),
('Gloire de Dijon',       null, 'Cl T','ab', 'climber',    'MIXED_CANE',         'cane',         1853, 'France',      'Rosa x hybrida'),

-- ── MINIATURES ────────────────────────────────────────────────────────────
('Cupcake',      null,  'Min', 'mp', 'miniature', 'NEW_GROWTH_DOMINANT', 'cane', 1981, 'United States', 'Rosa x hybrida'),
('Baby Love',    'SCR', 'Min', 'dy', 'miniature', 'NEW_GROWTH_DOMINANT', 'cane', 1992, 'England',       'Rosa x hybrida'),
('Starina',      'MEI', 'Min', 'or', 'miniature', 'NEW_GROWTH_DOMINANT', 'cane', 1965, 'France',        'Rosa x hybrida'),
('Rainbow''s End','SAV','Min', 'yb', 'miniature', 'NEW_GROWTH_DOMINANT', 'cane', 1984, 'United States', 'Rosa x hybrida'),
('Magic Carrousel','MOO','Min','rb', 'miniature', 'NEW_GROWTH_DOMINANT', 'cane', 1972, 'United States', 'Rosa x hybrida'),
('Rise ''n'' Shine', 'MOO','Min','my','miniature', 'NEW_GROWTH_DOMINANT', 'cane', 1977, 'United States', 'Rosa x hybrida'),
('Minnie Pearl', 'SAV', 'Min', 'lp', 'miniature', 'NEW_GROWTH_DOMINANT', 'cane', 1982, 'United States', 'Rosa x hybrida'),
('Popcorn',      null,  'Min', 'w',  'miniature', 'NEW_GROWTH_DOMINANT', 'cane', 1973, 'United States', 'Rosa x hybrida'),
('Cinderella',   null,  'Min', 'w',  'miniature', 'NEW_GROWTH_DOMINANT', 'cane', 1953, 'United States', 'Rosa x hybrida')

on conflict (canonical_name) do nothing;